// `NatsModule` — the NestJS dynamic module wrapping the framework-free
// `@nats-kit/core`.
//
// Public surface: `forRoot(options)` and `forRootAsync({ useFactory, inject })`
// — both generated by `NatsConfigurableModuleClass` (see nats.module-builder).
// `forRootAsync` is the primary production pattern (config usually comes from a
// `ConfigService`).
//
// Global-ness comes ONLY from the builder's `isGlobal` extra (default true),
// which the extras transform maps onto the DynamicModule `global` flag.
// Deliberately NO `@Global()` decorator here: Nest treats a module as global
// when EITHER the dynamic metadata has `global: true` OR the class carries the
// `@Global()` metadata (`container.isGlobalModule()`), so the decorator would
// turn an explicit `forRoot({ config, isGlobal: false })` opt-out into a
// silent no-op. Same recipe as `@nestjs/config`. With the default, once
// configured at the root every feature module gets `NatsService` / `KvService`
// / `JetStreamService` without re-importing `NatsModule`. This mirrors the
// internal NestJS module this package was extracted from, so migrating off a
// hand-rolled equivalent is a near-pure import swap.
//
// `NATS_OPTIONS` is exported alongside the services because it is public API
// (re-exported from the barrel) and consumers may `@Inject(NATS_OPTIONS)` the
// resolved options. The builder-generated `forRoot` / `forRootAsync` add the
// options PROVIDER but never export the token; Nest merges this decorator's
// metadata with the dynamic module's (scanner `reflectProviders` /
// `reflectExports`), so listing the token here completes the export.

import { Module } from "@nestjs/common";

import {
  NATS_OPTIONS,
  NatsConfigurableModuleClass,
} from "./nats.module-builder.js";
import { NatsService } from "./nats.service.js";
import { KvService } from "./kv.service.js";
import { JetStreamService } from "./jetstream.service.js";

@Module({
  providers: [NatsService, KvService, JetStreamService],
  exports: [NatsService, KvService, JetStreamService, NATS_OPTIONS],
})
export class NatsModule extends NatsConfigurableModuleClass {}
