// `NatsModule` — the NestJS dynamic module wrapping the framework-free
// `@nats-kit/core`.
//
// Public surface: `forRoot(options)` and `forRootAsync({ useFactory, inject })`
// — both generated by `NatsConfigurableModuleClass` (see nats.module-builder).
// `forRootAsync` is the primary production pattern (config usually comes from a
// `ConfigService`).
//
// `@Global()` — the NATS connection is an app-wide transport singleton. The
// builder already marks the module global via its `isGlobal` extra (default
// true); the decorator is kept as belt-and-suspenders and to make the global
// intent obvious at the class site. Once configured at the root, every feature
// module gets `NatsService` / `KvService` / `JetStreamService` without
// re-importing `NatsModule`. This mirrors the former in-repo `@repo/nats`
// module, so the re-consume is a near-pure import swap.

import { Global, Module } from "@nestjs/common";

import { NatsConfigurableModuleClass } from "./nats.module-builder.js";
import { NatsService } from "./nats.service.js";
import { KvService } from "./kv.service.js";
import { JetStreamService } from "./jetstream.service.js";

@Global()
@Module({
  providers: [NatsService, KvService, JetStreamService],
  exports: [NatsService, KvService, JetStreamService],
})
export class NatsModule extends NatsConfigurableModuleClass {}
